'use client'
import Link from "next/link"

const links=[{
  label:'Home',
  route:'/'
},
{
  label:'Pokemon',
  route:'/pokemon'
},
{
  label:'Tipos',
  route:'/types'
},
{
  label:'Berries',
  route:'/berries'
},
{
  label:'Movimientos',
  route:'/movements'
},
{
  label:'Ubicaciones',
  route:'/locations'
},
]

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <title>Pokemon APP</title>
      <body>
      <header>
        <nav>
          <ul>
            {links.map(({label,route})=>(
              <li key={route}>
                <Link href={route}>
                  {label}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </header>
        {children}
      </body>
    </html>
  )
}
